name: dcm2
region: nyc1
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
static_sites:
  - name: web
    github:
      repo: ascentdesign/dcm2
      branch: main
      deploy_on_push: true
    build_command: npm install --production=false --legacy-peer-deps && npm run build
    output_dir: /dist
    environment_slug: node-js
    envs:
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: VITE_CONVEX_URL
        value: "https://adventurous-grasshopper-203.convex.cloud"
    catchall_document: index.html
