name: dcm2
region: nyc1
services:
  - name: web
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: professional-xs
    github:
      repo: ascentdesign/dcm2
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: node_modules/.bin/serve -s dist -l 8080
    http_port: 8080
    envs:
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: NODE_ENV
        value: "production"
      - key: VITE_CONVEX_URL
        value: "https://adventurous-grasshopper-203.convex.cloud"
