name: dcm2
region: nyc3
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
services:
  - name: web
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    github:
      repo: ascentdesign/dcm2
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm ci --omit=dev && npm run build
    run_command: node node_modules/serve/build/main.js -s dist -l tcp://0.0.0.0:8080
    http_port: 8080
    envs:
      - key: NODE_ENV
        type: GENERAL
        scope: RUN_AND_BUILD_TIME
        value: "production"
      - key: VITE_CONVEX_URL
        type: GENERAL
        scope: RUN_AND_BUILD_TIME
        value: "https://adventurous-grasshopper-203.convex.cloud"
    routes:
      - path: /