name: dcm2
region: nyc
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
static_sites:
  - name: web
    environment_slug: html
    github:
      repo: ascentdesign/dcm2
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm install --no-audit --no-fund && npm run build -- --minify false
    output_dir: dist
    envs:
      - key: NODE_OPTIONS
        type: GENERAL
        scope: RUN_AND_BUILD_TIME
        value: "--max_old_space_size=512"
      - key: VITE_CONVEX_URL
        type: GENERAL
        scope: RUN_AND_BUILD_TIME
        value: "https://adventurous-grasshopper-203.convex.cloud"
    routes:
      - path: /
      - path: /*