name: dcm2
region: nyc1
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
static_sites:
  - name: web
    github:
      repo: ascentdesign/dcm2
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm ci && npm run build
    output_dir: /dist
    envs:
      - key: VITE_CONVEX_URL
        value: "https://adventurous-grasshopper-203.convex.cloud"
    routes:
      - path: /
    catchall_document: index.html
